services:
  couchbase:
    image: couchbase # https://hub.docker.com/_/couchbase
    restart: always
    environment:
      COUCHBASE_BUCKET: azimutt_sample
      COUCHBASE_ROOT_PASSWORD: password
    ports:
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"
      - "8094:8094"
      - "11210:11210"

  mariadb:
    image: mariadb # https://hub.docker.com/_/mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
      MARIADB_DATABASE: azimutt_sample
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3307"

  mongo:
    image: mongo # https://hub.docker.com/_/mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: azimutt_sample
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  mysql:
    image: mysql # https://hub.docker.com/_/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: azimutt_sample
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  postgres:
    image: postgres # https://hub.docker.com/_/postgres
    restart: always
    environment:
      POSTGRES_DB: azimutt_sample
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  sqlserver:
    image: mcr.microsoft.com/mssql/server # https://hub.docker.com/_/microsoft-mssql-server
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Pa$$w0rdddd # userid = 'sa'
    ports:
      - "1433:1433"

# https://hub.docker.com/_/oraclelinux
